name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force workflow run'
        required: true
        type: choice
        options: [yes, no]

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ 'oldstable', 'stable' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Download dependencies
        run: make deps

      - name: Run tests (panicnil=0)
        env:
          GODEBUG: panicnil=0
        run: make test

      - name: Run tests (panicnil=1)
        env:
          GODEBUG: panicnil=1
        run: make test
